### ISSUE TITLE
Хороший код...

### ISSUE THREAD

**Issue by SayHelloRoman** [TheKing-OfTime/Discord-interactions-Python-example#1]
Почему вы используйте синхронный requests в асинхронном боте, есть aiohttp для асинхронных запросов?
Почему названия функций CamelCase, а не snake_case?
Почему так много нарушений pep-8?
И это вы хотите сказать экземпляры? Да тут один говнокод.

**Comment by SayHelloRoman** [comment]
Разработчик ЧСВ которому не нужен pep-8

**Comment by TheKing-OfTime** [comment]
Too minor problems :D
